version: '3.9'

services:
  database:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5401:5432
    env_file:
      - .env

  certificationcenter:
    image: certificationcenter
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "alembic upgrade head && gunicorn app.main:app --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database

  certificationcenterfrontend:
    image: certificationcenterfrontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - certificationcenter
