version: '3.3'

services:
  database:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5401:5432
    env_file:
      - .env

  certificationcenter:
    image: certificationcenter
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --forwarded-allow-ips='*' --proxy-headers"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database

  certificationcenterfrontend:
    image: certificationcenterfrontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 80:80
