"""add order contact

Revision ID: 0378608b4e3b
Revises: 52e6773e449e
Create Date: 2022-07-26 19:03:28.093467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0378608b4e3b'
down_revision = '52e6773e449e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('contact_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_column('orders', 'region')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'contact_id')
    # ### end Alembic commands ###
