"""add contact region

Revision ID: 21aeda5dada2
Revises: 30bd2ab2d943
Create Date: 2022-07-24 10:15:58.530677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21aeda5dada2'
down_revision = '30bd2ab2d943'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('region', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'region')
    # ### end Alembic commands ###
