"""add place src

Revision ID: 30bd2ab2d943
Revises: 5fb51cd85e04
Create Date: 2022-07-23 13:52:54.946960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30bd2ab2d943'
down_revision = '5fb51cd85e04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('place_src', sa.String(), nullable=True))
    op.drop_column('contacts', 'coordinates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('coordinates', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('contacts', 'place_src')
    # ### end Alembic commands ###
