"""add mail config

Revision ID: 52e6773e449e
Revises: 21aeda5dada2
Create Date: 2022-07-24 13:25:18.707420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52e6773e449e'
down_revision = '21aeda5dada2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_config',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('MAIL_USERNAME', sa.String(), nullable=False),
    sa.Column('MAIL_PASSWORD', sa.String(), nullable=False),
    sa.Column('MAIL_FROM', sa.String(), nullable=False),
    sa.Column('MAIL_PORT', sa.Integer(), nullable=False),
    sa.Column('MAIL_SERVER', sa.String(), nullable=False),
    sa.Column('MAIL_FROM_NAME', sa.String(), nullable=False),
    sa.Column('MAIL_TLS', sa.Boolean(), nullable=False),
    sa.Column('MAIL_SSL', sa.Boolean(), nullable=False),
    sa.Column('USE_CREDENTIALS', sa.Boolean(), nullable=False),
    sa.Column('VALIDATE_CERTS', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_config_id'), 'email_config', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_config_id'), table_name='email_config')
    op.drop_table('email_config')
    # ### end Alembic commands ###
